### ISSUE TITLE
Support Traffic Splitting to Baseline, Stable, and Canary Pods in Experiment Step

### ISSUE THREAD

**Issue by vthiruveedhi** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#112]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.
* [x] I've included the version of the gateway API plugin
* [x] I've included the name and version of the gateway API provider I am using
* [x] I've included my Rollout Spec (anonymized if needed)

**Describe the bug**

Argo Rollouts provides support for the experiment step, including weighted traffic routing, as documented in the [Experiment Feature Overview](https://argoproj.github.io/argo-rollouts/features/experiment/#integration-with-rollouts). This feature automatically creates Service objects for experiment templates (e.g., baseline and canary) and dynamically splits traffic according to specified weights. For example, with the AWS ALB traffic router, Argo Rollouts updates Ingress annotations to route traffic across stable, baseline, and canary services during an experiment, reverting traffic post-experiment as needed. 

However, the GCP Gateway API plugin (argoproj-labs/gatewayAPI) **lacks equivalent support**. When using the experiment step with the Gateway API on Google Kubernetes Engine (GKE), the HTTPRoute is not updated to reflect traffic splits to experiment services, preventing the intended behavior.

**Example: Working Behavior with AWS ALB**
The AWS ALB traffic router demonstrates how this should work. Here’s an example from an Ingress annotation update:

During Experiment

```
[alb.ingress.kubernetes.io/actions.argo-rollouts-stable-service]: 
'{"Type":"forward","ForwardConfig":{"TargetGroups":[
  {"ServiceName":"argo-rollouts-canary-service","ServicePort":"443","Weight":0},
  {"ServiceName":"test-app-79fbf7c6f7-3-0-experiment-baseline","ServicePort":"443","Weight":5},
  {"ServiceName":"test-app-79fbf7c6f7-3-0-experiment-canary","ServicePort":"443","Weight":25},
  {"ServiceName":"argo-rollouts-stable-service","ServicePort":"443","Weight":70}]}}'
```

Traffic splits: 70% to stable, 5% to baseline, 25% to canary.
After Experiment (Post-Migration)

```
[alb.ingress.kubernetes.io/actions.argo-rollouts-stable-service]: 
'{"Type":"forward","ForwardConfig":{"TargetGroups":[
  {"ServiceName":"argo-rollouts-canary-service","ServicePort":"443","Weight":0},
  {"ServiceName":"argo-rollouts-stable-service","ServicePort":"443","Weight":100}]}}'
```

Traffic reverts: 100% to stable.
This shows Argo Rollouts effectively managing traffic splits for experiment services with the AWS ALB plugin.

**To Reproduce**

```
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: argo-rollouts-http-route
  namespace: gcp-test
  labels:
    managed-by: external-dns
spec:
  parentRefs:
  - kind: Gateway
    name: gcp-gateway
    sectionName: http
  - kind: Gateway
    name: gcp-gateway
    sectionName: https
  hostnames:
  - "example-dev.imbid.co"
  rules:
  - backendRefs:
    - name: argo-rollouts-stable-service
      port: 80
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: argo-rollouts-http-route-biz
  namespace: gcp-test
  labels:
    managed-by: external-dns
spec:
  parentRefs:
  - kind: Gateway
    name: gcp-gateway
    sectionName: http
  - kind: Gateway
    name: gcp-gateway
    sectionName: https
  hostnames:
  - "example-dev.thinknear.biz"
  rules:
  - backendRefs:
    - name: argo-rollouts-stable-service
      port: 80
    - name: argo-rollouts-canary-service
      port: 80
      weight: 0
---

# apiVersion: v1
# kind: Service
# metadata:
#   name: argo-rollouts-canary-service
#   namespace: gcp-test
# spec:
#   ports:
#   - port: 80
#     targetPort: http
#     protocol: TCP
#     name: http
#   selector:
#     app: rollouts-demo
---
apiVersion: v1
kind: Service
metadata:
  name: argo-rollouts-stable-service
  namespace: gcp-test
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rollouts-demo
---

# apiVersion: v1
# kind: Service
# metadata:
#   name: argo-rollouts-baseline-service
#   namespace: gcp-test
# spec:
#   ports:
#   - port: 80
#     targetPort: http
#     protocol: TCP
#     name: http
#   selector:
#     app: rollouts-demo
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: gcp-test
spec:
  replicas: 10
  strategy:
    canary:
      canaryService: argo-rollouts-canary-service # our created canary service
      stableService: argo-rollouts-stable-service # our created stable service
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: argo-rollouts-http-route # our created httproute
            namespace: kube-system
      steps:
      - experiment:
          duration: 15m
          templates:
          - name: experiment-baseline
            specRef: stable
            service:
              name: argo-rollouts-baseline-service
            weight: 5
            metadata:
              labels:
                app: rollouts-demo
          - name: experiment-canary
            specRef: canary
            service:
              name: argo-rollouts-canary-service-temp
            weight: 25
            metadata:
              labels:
                app: rollouts-demo
      - setWeight: 30
      - pause: { duration: 15m }
      ######
      # - setWeight: 30
      # - pause: { duration: 3m }
      # - setWeight: 60
      # - pause: { duration: 10m }
      # - setWeight: 100
      # - pause: { duration: 3m }
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: kostiscodefresh/summer-of-k8s-app:v2 # change to v2 for next version
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
---

apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gcp-gateway
  namespace: kube-system
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    networking.gke.io/frontend-config: "test-gateway-frontendconfig"
spec:
  gatewayClassName: "gke-l7-global-external-managed"
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: "example-dev.domain.co"
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: "wildcard-cert-secret"
      mode: Terminate
  - name: http
    port: 80
    protocol: HTTP
    hostname: "example-dev.domain.co"
    allowedRoutes:
      namespaces:
        from: All
---

```

**Expected behavior**

Based on the experiment documentation and parity with other traffic routers:

1. Service Creation: During the experiment step, Argo Rollouts should auto-generate Service objects for experiment templates, e.g., test-app-experiment-baseline and test-app-experiment-canary.
2. Traffic Splitting: The Gateway API plugin should update the HTTPRoute to split traffic, e.g.:
   70% to argo-rollouts-stable-service (stable pods).
   5% to test-app-experiment-baseline (baseline pods).
   25% to test-app-experiment-canary (canary pods).
3. Post-Experiment: After the experiment duration (e.g., with setWeight: 0), traffic should revert to 100% on argo-rollouts-stable-service.

**Actual Behavior**

1. **What Happens**: The experiment pods and associated Service objects (e.g., test-app-experiment-baseline, test-app-experiment-canary) are created as expected. However, the HTTPRoute is not updated to include backendRefs or weights for these experiment services.
2. **Observed Issue**: Traffic routing does not occur. Plugin logs reveal errors indicating it cannot find or apply the necessary backendRefs for the experiment services, halting traffic splitting.
3. **Impact**: Users cannot leverage the experiment step to test baseline and canary versions with real traffic on GKE, limiting progressive delivery capabilities.

**Screenshots**

the httproute is not being updated. 

![Image](https://github.com/user-attachments/assets/477dd634-387f-4ab9-b980-a4b4c80392f2)

**Version**

argo-rollouts-2.39.0   	v1.8.0

controller:
  trafficRouterPlugins:
  - name: "argoproj-labs/gatewayAPI"
    location: "https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/releases/download/v0.5.0/gatewayapi-plugin-linux-amd64"

**Logs**

```
Entering degraded mode for NEG gcp-test/argo-rollouts-baseline-service-k8s1-94b23160-gcp-test-argo-rollouts-baseline-serv-8-20a80a03-http/80-http-GCE_VM_IP_PORT-L7 due to sync err: endpoint count from endpointPodMap cannot be zero
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
