### ISSUE TITLE
SetHeader option support

### ISSUE THREAD

**Issue by mvishnevsky** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#21]
Hi,
I was wondering if there is a plan or a roadmap for when the plugin will support the SetHeader option.
Thank you!

**Comment by cevret** [comment]
I am also interested in this. Thanks!

**Comment by Philipp-Plotnikov** [comment]
Hi, thank you for idea. I think it will be nice feature for the plugin. I think we can implement it and I have suggestion how we can do it.
1. Add setHeaderRoutes field under argoproj-labs/gatewayAPI in argo rollouts manifest
2. We will create additional httpRoute resource that will overwrite the main httpRoute using the following rules(they are identical to the gateway api rules)
You can find them here
[https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteRule](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.HTTPRouteRule)

I tested it locally. It works.

The structure of setHeaderRoutes is
setHeaderRoutes:
  - headers:
    - name: string
      value: string
    ...
  ...
The data inside of one block of headers is connected with logical operator and.
The data of different blocks "headers" is connected with logical operator or
What do you think ?
@kostis-codefresh @zachaller

**Comment by Philipp-Plotnikov** [comment]
The structure of Argo Rollouts manifest will be the following
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:green
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
  strategy:
    canary:
      stableService: stable-service
      canaryService: canary-service
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            namespace: default
            httpRoute: http-route
      steps:
        - setWeight: 20
        - setHeaderRoute: # enable header based traffic routing where
             name: "set-header-1"
             match:
               - headerName: Custom-Header1 # Custom-Header1=Mozilla
                  headerValue:
                    exact: Mozilla
               - headerName: Custom-Header2 # or Custom-Header2 has a prefix Mozilla
                  headerValue:
                    prefix: Mozilla
               - headerName: Custom-Header3 # or Custom-Header3 value match regex: Mozilla(.*)
                  headerValue:
                    regex: Mozilla(.*)
        - pause: {}
        - setHeaderRoute:
             name: "set-header-1"
```
If match header type in argo manifest is exact we use header match type Exact in HttpRoute
If match header type in argo manifest is regex we use header match type RegularExpression in HttpRoute
If match header type in argo manifest is prefix we use header match type RegularExpression in HttpRoute and add .* to the end of <user value> .
<user value>.*
