### ISSUE TITLE
Support multiple HTTPRoute resources per rollout

### ISSUE THREAD

**Issue by svrakitin** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#33]
It's possible that the same rollout might need to change backend weights in multiple `HTTPRoute`/`TCPRoute` resources.
I'm running into a situation, where I have multiple `HTTPRoute` resources per service and can only change one.

This is similar to https://github.com/argoproj/argo-rollouts/issues/1100, which is about Istio `VirtualService` resources.

Example:
```yaml
plugins:
  argoproj-labs/gatewayAPI:
    httpRoutes: 
      - first
      - second
    namespace: default
```

If you think it makes sense I'm up for contributing.

**Comment by Philipp-Plotnikov** [comment]
Hi @svrakitin ! Thank you for your contribution!! I think its really nice feature! But I think maybe we will support only one way of structure ? For example like this ? And the same with tcpRoutes. I think it will be easier to support code
```
plugins:
  argoproj-labs/gatewayAPI:
    httpRoutes: 
      - first
      - second
 ```
