### ISSUE TITLE
Config map ref broken while upgrading to 0.1.0 version from 0.0.1

### ISSUE THREAD

**Issue by komal-SkyNET** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#36]
Error from the argo-controller pods after upgrading to v0.1.0
```
time="2024-02-13T06:47:11Z" level=info msg="Found 1 TrafficRouting Reconcilers" namespace=test-argo-gamma rollout=gap-app-argo
time="2024-02-13T06:47:11Z" level=info msg="Reconciling TrafficRouting with type 'GatewayAPI'" namespace=test-argo-gamma rollout=gap-app-argo
time="2024-02-13T06:47:11Z" level=error msg="roCtx.reconcile err failed to remove managed routes via plugin: configmaps \"argo-gatewayapi-configmap\" not found" generation=2 namespace=test-argo-gamma resourceVersion=348232258 rollout=gap-app-argo
time="2024-02-13T06:47:11Z" level=info msg="Reconciliation completed" generation=2 namespace=test-argo-gamma resourceVersion=348232258 rollout=gap-app-argo time_ms=23.592025
time="2024-02-13T06:47:11Z" level=error msg="rollout syncHandler error: failed to remove managed routes via plugin: configmaps \"argo-gatewayapi-configmap\" not found" namespace=test-argo-gamma rollout=gap-app-argo
time="2024-02-13T06:47:11Z" level=info msg="rollout syncHandler queue retries: 38 : key \"test-argo-gamma/gap-app-argo\"" namespace=test-argo-gamma rollout=gap-app-argo
time="2024-02-13T06:47:11Z" level=error msg="failed to remove managed routes via plugin: configmaps \"argo-gatewayapi-configmap\" not found\n" error="<nil>"
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-config 
  namespace: argo-rollouts 
data:
  trafficRouterPlugins: |-
    - name: "argoproj-labs/gatewayAPI"
      location: "https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/releases/download/v0.1.0/gateway-api-plugin-linux-amd64"
```

Reverting back to v0.0.1 works fine. 

Is there a ReadME with instructions for the upgrade to 0.1.0? How can I help?
