### ISSUE TITLE
Canary support with argo rolll outs with kong traffic provider does not work seamlessly

### ISSUE THREAD

**Issue by som-kanade-zepto** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#65]
Checklist:

Argo roll out image version :  v1.7.0
Kong Version: 3.5
Argo roll out app version: 2.37.2

**Describe the bug**

<Tried Canary support with argo roll outs with kong traffic provider everything works and rollout happens BUT after some time (not fixed). other APIs which are routed via same gateway start failing where as there are no changes made to those http routes>

**To Reproduce**

1. Install argo roll out
2. Install kong ingress controller 
3. Followed this doc (https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/tree/main/examples/kong)
4. Everything works as expected 
5. Existing API which shares same gateway start giving 5xx error where as no changes made to that object starts failing 
6. Deleting http object of sample app created using above documentation will fix the issue 

**Expected behavior**

All routes should without any issues 

**Screenshots**

We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.

**Version**

Argo roll out image version :  v1.7.0
Argo roll out app version: 2.37.2

**Logs**

No specific errors in roll out controller when this issue happend

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by Philipp-Plotnikov** [comment]
Hi, you installed argo rollouts and it works, but other APIs using the same Gateway stopped to work and other APIs also uses HTTPRoute resources ? Can you say HTTPRoutes configurations have intersecations in rules, please ? It seems it is related with matching precedence https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRouteRule
Did you check it ?

**Comment by Philipp-Plotnikov** [comment]
@som-kanade-zepto did you solve the problem ? If yes, can you share your solution, please ?

**Comment by som-kanade-zepto** [comment]
No there is no intersection between API Paths of 2 services that are failing

**Comment by Philipp-Plotnikov** [comment]
@som-kanade-zepto did you check the logs of Kong controller and argo rollouts controller ? Did you see any errors or warnings there ?

**Comment by som-kanade-zepto** [comment]
I was able to only see 5xx errors in kong nothing related to this with timeouts and very generic 5xx errors nothing related to this

**Comment by Philipp-Plotnikov** [comment]
Is it similar to create these 2 HTTPRoutes
```yaml
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: test-httproute
  annotations:
    konghq.com/strip-path: 'true'
spec:
  parentRefs:
  - kind: Gateway
    name: kong
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1/cart  
    backendRefs:
    - name: argo-rollouts-stable-service
      kind: Service
      port: 80
      weight: 50
    - name: argo-rollouts-canary-service
      kind: Service
      port: 80
      weight: 50
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: argo-rollouts-test-httproute
  annotations:
    konghq.com/strip-path: 'true'
spec:
  parentRefs:
  - kind: Gateway
    name: kong
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /test  
    backendRefs:
    - name: argo-rollouts-stable-service
      kind: Service
      port: 80
    - name: argo-rollouts-canary-service
      kind: Service
      port: 80
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: default
spec:
  revisionHistoryLimit: 1
  replicas: 3
  strategy:
    canary:
      canaryService: argo-rollouts-canary-service # our created canary service
      stableService: argo-rollouts-stable-service # our created stable service
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: argo-rollouts-test-httproute # our created httproute
            namespace: default
      steps:
      - setWeight: 30
      - pause: {}
      - setWeight: 60
      - pause: {}
      - setWeight: 100
      - pause: {} 
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: kostiscodefresh/summer-of-k8s-app:v2 # change to v2 for next version
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
```
