### ISSUE TITLE
failed to set weight via plugin: an empty namespace may not be set when a resource name is provided

### ISSUE THREAD

**Issue by avinovarov** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#67]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.
* [x] I've included the version of the gateway API plugin
* [x] I've included my Rollout Spec (anonymized if needed)

**Describe the bug**

In sandbox, while gateway and HTTPRoute let the traffic from outside of the cluster to the pods, the Rollout gives the error:

`Warning  TrafficRoutingError     82s (x21 over 3m18s)  rollouts-controller  failed to set weight via plugin: an empty namespace may not be set when a resource name is provided`

**Gateway and HTTPRoute seem to work fine, I am able to curl the (nginx) pod and get response, the only issue is the Rollout which is stuck and never resolves.**

Rollout described:
```
Name:         app
Namespace:    test
API Version:  argoproj.io/v1alpha1
Kind:         Rollout

Spec:
  Replicas:  2
  Rollback Window:
    Revisions:  3
  Strategy:
    Canary:
      Canary Service:   canary
      Max Surge:        25%
      Max Unavailable:  0
      Stable Service:   stable
      Steps:
        Set Weight:  1
        Pause:
          Duration:  1m
        Set Weight:  10
        Pause:
          Duration:  1m
        Set Weight:  50
        Pause:
          Duration:  1m
        Set Weight:  100
      Traffic Routing:
        Plugins:
          argoproj-labs/gatewayAPI:
            Http Route:  httproute
  Workload Ref:
    API Version:  apps/v1
    Kind:         Deployment
    Name:         deployment-ref
    Scale Down:   onsuccess
Status:
  Blue Green:
  Canary:
  Conditions:
    Last Transition Time:        2024-08-09T10:56:10Z
    Last Update Time:            2024-08-09T10:56:10Z
    Message:                     Rollout does not have minimum availability
    Reason:                      AvailableReason
    Status:                      False
    Type:                        Available
    Last Transition Time:        2024-08-09T10:56:10Z
    Last Update Time:            2024-08-09T10:56:10Z
    Message:                     RolloutCompleted
    Reason:                      RolloutCompleted
    Status:                      False
    Type:                        Completed
    Last Transition Time:        2024-08-09T10:56:10Z
    Last Update Time:            2024-08-09T10:56:10Z
    Message:                     Created new replica set "app-6c5784568f"
    Reason:                      NewReplicaSetCreated
    Status:                      True
    Type:                        Progressing
  Current Pod Hash:              6c5784568f
  Current Step Hash:             7b89779767
  Current Step Index:            0
  Message:                       more replicas need to be updated
  Observed Generation:           1
  Phase:                         Progressing
  Selector:                      app=app
  Workload Observed Generation:  6
Events:
  Type     Reason                  Age                   From                 Message
  ----     ------                  ----                  ----                 -------
  Normal   RolloutAddedToInformer  3m18s                 rollouts-controller  Rollout resource added to informer: test/app
  Normal   RolloutNotCompleted     3m18s                 rollouts-controller  Rollout not completed, started update to revision 1 (6c5784568f)
  Normal   RolloutUpdated          3m18s                 rollouts-controller  Rollout updated to revision 1
  Normal   NewReplicaSetCreated    3m18s                 rollouts-controller  Created ReplicaSet app-6c5784568f (revision 1)
  Warning  TrafficRoutingError     82s (x21 over 3m18s)  rollouts-controller  failed to set weight via plugin: an empty namespace may not be set when a resource name is provided
```

Sandbox setup: a Rollout using Deployment reference, canary/stable services, Gateway on Cilium, HTTPRoute.

Rollout and Deployment specs:

```
kind: Rollout
apiVersion: argoproj.io/v1alpha1
metadata:
  name: app
spec:
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-ref
    scaleDown: onsuccess

  replicas: 2

  rollbackWindow:
    revisions: 3

  strategy:
    canary:
      stableService: stable
      canaryService: canary
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: httproute
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 1
      - pause:
          duration: 1m
      - setWeight: 10
      - pause:
          duration: 1m
      - setWeight: 50
      - pause:
          duration: 1m
      - setWeight: 100

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment-ref
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: test
          image: nginx:1.26
          volumeMounts:
            - name: index
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
              readOnly: true
          resources:
            requests:
              memory: 250Mi
              cpu: 100m
      volumes:
        - name: index
          configMap:
            name: index1
```

**To Reproduce**

Create the setup as described, rollout is stuck with the error described.

**Expected behavior**

Rollout is expected to follow the strategy and set the weight accordingly. 

**Screenshots**

-

**Version**

Argo Rollouts: 1.7.1
Gateway plugin: 0.3.0

**Logs**

```
time="2024-08-09T11:01:13Z" level=info msg="Reconciliation completed" generation=3 namespace=camp resourceVersion=10170277 rollout=camp-be-app-main time_ms=2.957633
time="2024-08-09T11:01:13Z" level=error msg="rollout syncHandler error: failed to set weight via plugin: an empty namespace may not be set when a resource name is provided" namespace=camp rollout=camp-be-app-main
time="2024-08-09T11:01:13Z" level=info msg="rollout syncHandler queue retries: 18757 : key \"camp/camp-be-app-main\"" namespace=camp rollout=camp-be-app-main
2024-08-09T11:01:13.647Z [DEBUG] plugin.gatewayAPI: time="2024-08-09T11:01:13Z" level=info msg="[SetWeight] plugin \"argoproj-labs/gatewayAPI\" controls HTTPRoutes: [httproute]" plugin=trafficrouter
time="2024-08-09T11:01:13Z" level=error msg="failed to set weight via plugin: an empty namespace may not be set when a resource name is provided" error="<nil>"
time="2024-08-09T11:01:13Z" level=info msg="Event(v1.ObjectReference{Kind:\"Rollout\", Namespace:\"camp\", Name:\"camp-be-app-main\", UID:\"acaf39b0-d7a5-441b-8fbd-72e4b261186c\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"10170277\", FieldPath:\"\"}): type: 'Warning' reason: 'TrafficRoutingError' failed to set weight via plugin: an empty namespace may not be set when a resource name is provided"
time="2024-08-09T11:01:13Z" level=warning msg="failed to set weight via plugin: an empty namespace may not be set when a resource name is provided" event_reason=TrafficRoutingError namespace=camp rollout=camp-fe-app-main
time="2024-08-09T11:01:13Z" level=error msg="roCtx.reconcile err failed to set weight via plugin: an empty namespace may not be set when a resource name is provided" generation=3 namespace=camp resourceVersion=10170274 rollout=camp-fe-app-main
time="2024-08-09T11:01:13Z" level=info msg="Reconciliation completed" generation=3 namespace=camp resourceVersion=10170274 rollout=camp-fe-app-main time_ms=3.186036
time="2024-08-09T11:01:13Z" level=error msg="rollout syncHandler error: failed to set weight via plugin: an empty namespace may not be set when a resource name is provided" namespace=camp rollout=camp-fe-app-main
time="2024-08-09T11:01:13Z" level=info msg="rollout syncHandler queue retries: 18757 : key \"camp/camp-fe-app-main\"" namespace=camp rollout=camp-fe-app-main
time="2024-08-09T11:01:13Z" level=error msg="failed to set weight via plugin: an empty namespace may not be set when a resource name is provided" error="<nil>"
time="2024-08-09T11:01:13Z" level=info msg="Event(v1.ObjectReference{Kind:\"Rollout\", Namespace:\"camp\", Name:\"camp-fe-app-main\", UID:\"79fce36b-7b32-439b-937f-f703a9ddd53d\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"10170274\", FieldPath:\"\"}): type: 'Warning' reason: 'TrafficRoutingError' failed to set weight via plugin: an empty namespace may not be set when a resource name is provided"
time="2024-08-09T11:01:16Z" level=info msg="Started syncing rollout" generation=1 namespace=test resourceVersion=11928163 rollout=app
time="2024-08-09T11:01:16Z" level=info msg="delaying service switch from  to 6c5784568f: ReplicaSet not fully available" namespace=test rollout=app service=canary
time="2024-08-09T11:01:16Z" level=info msg="Found 1 TrafficRouting Reconcilers" namespace=test rollout=app
time="2024-08-09T11:01:16Z" level=info msg="Reconciling TrafficRouting with type 'GatewayAPI'" namespace=test rollout=app
2024-08-09T11:01:16.822Z [DEBUG] plugin.gatewayAPI: time="2024-08-09T11:01:16Z" level=info msg="[SetWeight] plugin \"argoproj-labs/gatewayAPI\" controls HTTPRoutes: [httproute]" plugin=trafficrouter
time="2024-08-09T11:01:16Z" level=warning msg="failed to set weight via plugin: an empty namespace may not be set when a resource name is provided" event_reason=TrafficRoutingError namespace=test rollout=app
time="2024-08-09T11:01:16Z" level=error msg="roCtx.reconcile err failed to set weight via plugin: an empty namespace may not be set when a resource name is provided" generation=1 namespace=test resourceVersion=11928163 rollout=app
time="2024-08-09T11:01:16Z" level=info msg="Reconciliation completed" generation=1 namespace=test resourceVersion=11928163 rollout=app time_ms=2.601529
time="2024-08-09T11:01:16Z" level=error msg="rollout syncHandler error: failed to set weight via plugin: an empty namespace may not be set when a resource name is provided" namespace=test rollout=app
time="2024-08-09T11:01:16Z" level=info msg="rollout syncHandler queue retries: 44 : key \"test/app\"" namespace=test rollout=app
time="2024-08-09T11:01:16Z" level=error msg="failed to set weight via plugin: an empty namespace may not be set when a resource name is provided" error="<nil>"
time="2024-08-09T11:01:16Z" level=info msg="Event(v1.ObjectReference{Kind:\"Rollout\", Namespace:\"test\", Name:\"app\", UID:\"313d9b58-a8d6-4513-ab63-5f449ff0b206\", APIVersion:\"argoproj.io/v1alpha1\", ResourceVersion:\"11928163\", FieldPath:\"\"}): type: 'Warning' reason: 'TrafficRoutingError' failed to set weight via plugin: an empty namespace may not be set when a resource name is provided"```

---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by avinovarov** [comment]
The solution is to explicitly specify the `Namespace` in trafficRouting plugin settings, in Rollout spec:

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
spec:
  strategy:
    canary:
      stableService: stable
      canaryService: canary
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: httproute
            namespace: test # <<< Specifying namespace is REQUIRED here
```

Well, at least this error is now googlable :)
