### ISSUE TITLE
Update the gateway-controller-role ClusterRole permissions

### ISSUE THREAD

**Issue by Chimbu-DoiT** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#68]
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've included the version of argo rollouts.
* [x] I've included the version of the gateway API plugin
* [x] I've included my Rollout Spec (anonymized if needed)

**Describe the bug**

The `ClusterRole` resource `gateway-controller-role` currently has overly permissive permissions, causing concerns as argo-rollouts do not require all these permissions in the cluster. The permissions should be restricted to modifying the httpRoute resource only.

**To Reproduce**

Check the configuration in https://rollouts-plugin-trafficrouter-gatewayapi.readthedocs.io/en/latest/quick-start/#step-3-allow-argo-rollouts-to-edit-http-routes

**Expected behavior**

The permission should be limited like below 

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-controller-role
  namespace: argo-rollouts
rules:
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
    verbs:
      - get
      - list
      - patch
      - update
      - watch
 ```

**Screenshots**

N/A

**Version**

argo-rollout version - v1.7.1
gateway-api-plugin version - 

**Logs**
N/A

```
---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
