### ISSUE TITLE
Experience running this plugin with gRPCRoutes in a linkerd-meshed cluster

### ISSUE THREAD

**Issue by FredrikAugust** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#75]
It appears we're among the first to test out this plugin with linkerd and grpcroutes so I thought I'd share some knowledge which might help others.

We're running a custom build (just from trunk) hosted in s3 and injecting that into argo rollouts using the helm chart:

```yaml
        controller:
          trafficRouterPlugins:
            trafficRouterPlugins: |-
              - name: "argoproj-labs/gatewayAPI"
                location: "https://********/gatewayapi-plugin-linux-amd64"

```

Our grpcRoutes look something like this:

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  annotations:
    retry.linkerd.io/grpc: cancelled,deadline-exceeded,resource-exhausted,unavailable,internal
    retry.linkerd.io/limit: "3"
    retry.linkerd.io/timeout: 300ms
  name: abc-grpc-route-query
  namespace: abc
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: init
    port: 80
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: xyz
      port: 80
      weight: 100
    - group: ""
      kind: Service
      name: xyz-canary
      port: 80
      weight: 0
    matches:
    - method:
        method: xyz
        service: abc.xyz
        type: Exact
```

Our rollouts have the following canary strategy configuration:

```yaml
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            grpcRoutes:
            - name: xyz-read-grpc-route-query
            - name: xyz-read-grpc-route-command
            namespace: init
```

We just rolled this out to our staging cluster, and the grpcRoutes seem to update just fine in realtime like they're supposed to. I'm going to try to get some metrics from linkerd to see how it all works and post that here within a couple of days.
