### ISSUE TITLE
Header based routing does not work if original HTTP route has filters on it

### ISSUE THREAD

**Issue by kostis-codefresh** [argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi#87]
The header based routing example only works if the existing HTTP route has no filters.

This works
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: my-smart-route
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: default
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /     
    backendRefs:
     - name: argo-rollouts-stable-service
       kind: Service
       port: 80
     - name: argo-rollouts-canary-service
       kind: Service
       port: 80
```

This does **not** work 

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: my-smart-route
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: default
  rules:
  - matches:
    - path:
        type: PathPrefix  
        value: /smart/ 
     filters:
       - type: URLRewrite
         urlRewrite:
           path:
             type: ReplacePrefixMatch
             replacePrefixMatch: / 
    backendRefs:
     - name: argo-rollouts-stable-service
       kind: Service
       port: 80
     - name: argo-rollouts-canary-service
       kind: Service
       port: 80
```

Full example is [here](https://github.com/kostis-codefresh/rollouts-header-routing-example/tree/main/dynamic-routing).

When a header based http route is created it should copy all the properties from the original  route (including filters)

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.
